### ISSUE TITLE
运行时获取不到debugtalk下的方法

### ISSUE THREAD

**Issue by TaylorYY** [httprunner/hrp#117]
方法buildHashicorpPlugin\removeHashicorpPlugin在runner_test.go里面，导致执行runner.go时，没有执行到buildHashicorpPlugin\removeHashicorpPlugin，所以运行时获取不到debugtalk下的方法

**Comment by debugtalk** [comment]
@TaylorYY 这两个方法本来就是用于单元测试的。
你说的运行时获取不到debugtalk下的方法，可以贴下你的运行日志么？

**Comment by TaylorYY** [comment]
@debugtalk 我明白你的意思了，我是修改了部分runner.go的代码，使其支持用josn格式TestCase对应的结构体去执行，在这过程中发现执行时少了这两个方法，看了plugin介绍，知道你这么写的用意，谢谢
