### ISSUE TITLE
json文件body数据transNo字段在执行后打印的控制台数据变成了traNo

### ISSUE THREAD

**Issue by lugxin** [httprunner/hrp#123]
请求body里面的数据：
"body": {
                    "secretKey": "a6e5c609787f0be624b8f3ce1da4934f",
                    "privateKey": "Mdsfsdfsdfsdfsdf",
                    "plainText": {
                        "cmd": "BANK",
                        "extra": "数据",
                        "callbackUrl":"/single/orderCallBack",
                        "orderInfo":{
                            "transNo":"888123456",
                            "accountNo":"3245345",
                            "accountName":"fndtest003",
                            "mobile":"16190000004",
                            "papersType":"OTHER",
                            "cardNo":"77882224",
                            "amount":0.02,
                            "bankCardLocation":"bank",
                            "remark":"API"
                        }
                    }
                }
![image](https://user-images.githubusercontent.com/4596446/155705959-aa6a22a3-5196-4773-bfc2-086309867788.png)

**Comment by debugtalk** [comment]
@lugxin 这个应该是你 IDE terminal 打印截断后有 2 个字符没有显示出来。
