### ISSUE TITLE
startproject in scaffold needs go sdk

### ISSUE THREAD

**Issue by FrankWangJQ** [httprunner/hrp#125]
尝试安装时报错:go语言环境问题(文档中有提过:无需安装任何运行时环境依赖)

version:0.6.2
system: Mac OS 12.2(Inter)

wangjianqing@wangjianqingdeMacBook-Pro PycharmProjects % hrp startproject apiTest_huanQiu
3:07AM INF Set log to color console other than JSON format.
3:07AM ??? Set log level
3:07AM INF create new scaffold project projectName=apiTest_huanQiu
3:07AM INF create folder path=apiTest_huanQiu
3:07AM INF create folder path=apiTest_huanQiu/har
3:07AM INF create folder path=apiTest_huanQiu/testcases
3:07AM INF create folder path=apiTest_huanQiu/plugin
3:07AM INF create folder path=apiTest_huanQiu/reports
3:07AM INF dump data to json path=/Users/wangjianqing/PycharmProjects/apiTest_huanQiu/testcases/demo.json
3:07AM INF dump data to yaml path=/Users/wangjianqing/PycharmProjects/apiTest_huanQiu/testcases/demo.yaml
3:07AM INF create file path=apiTest_huanQiu/plugin/debugtalk.go
3:07AM INF exec command cmd="go mod init plugin" cwd=apiTest_huanQiu/plugin
3:07AM **ERR exec command failed error="exec: \"go\": executable file not found in $PATH" output=**

解决环境依赖,安装go语言环境后
提示权限问题ERR exec command failed error="exit status 1" output="warning: GOPATH set to GOROOT (/usr/local/go) has no effect\ngo: could not create module cache: mkdir /usr/local/go/pkg/mod: permission denied"

更改文件路径权限后脚手架创建成功

**Comment by debugtalk** [comment]
@FrankWangJQ hrp 本来是无需依赖可直接运行的，但在脚手架工具中，考虑到使用自定义函数是很普遍的情况（对应之前 Python 版的 debugtalk.py），因此在示例中增加了这部分。
而针对 go 语言来说，需要编译运行，因此就少不了安装 go 语言环境。

感谢反馈哈，这块儿我再想下怎么降低新人上手负担。

**Comment by debugtalk** [comment]
@FrankWangJQ 当前已经支持在脚手架生成项目时选择插件语言了

```bash
$ hrp startproject -h  
create a scaffold project

Usage:
  hrp startproject $project_name [flags]

Flags:
      --go              generate hashicorp go plugin
  -h, --help            help for startproject
      --ignore-plugin   ignore function plugin
      --py              generate hashicorp python plugin (default true)

Global Flags:
      --log-json           set log to json format
  -l, --log-level string   set log level (default "INFO")
```
